version: '3.1'
services:
  # jdbc:postgresql://localhost/postgresql
  # username: postgresql
  # password: mysecretpassword
  postgres:
    container_name: 'orange-fleet'
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
volumes:
  mysql_storage: