-- Fake data for the Ubay marketplace

insert into category (name, description) values ('Cardify', 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum');
insert into category (name, description) values ('Tresom', 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus');
insert into category (name, description) values ('Overhold', 'habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit');
insert into category (name, description) values ('Keylex', 'velit donec diam neque vestibulum eget vulputate ut ultrices vel');
insert into category (name, description) values ('Viva', 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu');
insert into category (name, description) values ('Ronstring', 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed');
insert into category (name, description) values ('Sonsing', 'sollicitudin mi sit amet lobortis sapien sapien non mi integer');
insert into category (name, description) values ('Duobam', 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet');
insert into category (name, description) values ('Rank', 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris');
insert into category (name, description) values ('Mat Lam Tam', 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti');

insert into client (name, last_name, address, city, birth_date, gender) values ('Linet', 'Yeskin', '7 Talmadge Pass', 'Buckland', '2022-02-19', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ('Dorelle', 'Moores', '5 Lakeland Circle', 'Quba', '2021-08-23', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ('Brewer', 'Robel', '6442 Cody Lane', 'Youxi Chengguanzhen', '2021-07-26', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ('Sapphira', 'Iddens', '9660 Norway Maple Lane', 'Wawrzeńczyce', '2021-04-15', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ('Sonny', 'Ney', '9353 Roth Place', 'Hane', '2021-05-03', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ('Jerrie', 'Fetherston', '1 Twin Pines Drive', 'Huangling', '2021-05-22', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ('Leroy', 'Yerrill', '49253 Russell Crossing', 'Sestroretsk', '2021-09-05', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ('Cleveland', 'Hatherall', '5 Nelson Place', 'Ryazhsk', '2022-03-04', 'female');
insert into client (name, last_name, address, city, birth_date, gender) values ('Pegeen', 'Scurrah', '3390 Thompson Trail', 'Dahuang', '2022-03-18', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Domeniga', 'De Cruz', '869 Loftsgordon Plaza', 'Shiree', '2022-01-28', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Regan', 'Stollen', '94 Browning Avenue', 'Maricá', '2021-11-19', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Eleanor', 'Siveyer', '21211 Ridgeview Junction', 'Kayukembang', '2021-06-30', 'female');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Jeni', 'Bridgwater', '18 Declaration Park', 'Kilju', '2021-12-28', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Jules', 'Bramelt', '8059 Ramsey Way', 'Malgobek', '2021-04-17', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Vanny', 'Ebbin', '76 Hoard Place', 'Montgomery', '2022-02-22', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Kean', 'Volant', '7435 Sutherland Junction', 'Kinatakutan', '2022-01-18', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Sergio', 'Harden', '62524 Warbler Junction', 'Sandymount', '2022-03-07', 'female');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Querida', 'Badrock', '45495 Hooker Terrace', 'Jieshan', '2022-01-10', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Elicia', 'Joincey', '91186 Elka Trail', 'Suure-Jaani', '2021-08-13', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Madonna', 'Treharne', '1 Dexter Crossing', 'Louisville', '2021-12-22', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Zebedee', 'Choupin', '55 Summit Court', 'Wa’eryi', '2021-07-21', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Emelen', 'Laurisch', '062 Clarendon Park', 'Guaratuba', '2021-11-29', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Delia', 'Ilsley', '01 Stephen Circle', 'Qintang', '2021-09-05', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Alexandre', 'Gioan', '28207 Bayside Hill', 'Alupay', '2021-07-07', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Lani', 'Dimitru', '8828 Park Meadow Hill', 'Lolodorf', '2022-01-30', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Emmye', 'Abbotts', '88084 Marcy Junction', 'Duraykīsh', '2022-01-02', 'female');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Kienan', 'de Aguirre', '66 Little Fleur Lane', 'Kangdong-ŭp', '2021-05-16', 'female');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Vivian', 'Attwill', '71 5th Drive', 'Mstsislaw', '2021-07-01', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Marina', 'Stickney', '327 Artisan Street', 'Wąsosz', '2021-04-07', 'other');
insert into client (name, last_name, address, city, birth_date, gender) values ( 'Waverly', 'Barstow', '275 Service Plaza', 'Póvoa', '2021-10-02', 'male');
insert into client (name, last_name, address, city, birth_date, gender) values ('username','lastname','address', 'city','2022-02-19', 'other');


-- password = BCrypt("password")
insert into login_credentials (username, password, kind, user_id) values ('kbrimilcombe0', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 1);
insert into login_credentials (username, password, kind, user_id) values ('nfarnes1', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 2);
insert into login_credentials (username, password, kind, user_id) values ('iramey2', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 3);
insert into login_credentials (username, password, kind, user_id) values ('hroyston3', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 4);
insert into login_credentials (username, password, kind, user_id) values ('cstarie4', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 5);
insert into login_credentials (username, password, kind, user_id) values ('gwaight5', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 6);
insert into login_credentials (username, password, kind, user_id) values ('ktrevance6', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 7);
insert into login_credentials (username, password, kind, user_id) values ('vglasper7', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 8);
insert into login_credentials (username, password, kind, user_id) values ('jcremer8', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 9);
insert into login_credentials (username, password, kind, user_id) values ('vscading9', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 10);
insert into login_credentials (username, password, kind, user_id) values ('acloughtona', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 11);
insert into login_credentials (username, password, kind, user_id) values ('bculwenb', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 12);
insert into login_credentials (username, password, kind, user_id) values ('rleamyc', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 13);
insert into login_credentials (username, password, kind, user_id) values ('gwyllisd', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 14);
insert into login_credentials (username, password, kind, user_id) values ('ghaggare', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 15);
insert into login_credentials (username, password, kind, user_id) values ('bofahertyf', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 16);
insert into login_credentials (username, password, kind, user_id) values ('glythgoeg', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 17);
insert into login_credentials (username, password, kind, user_id) values ('hlafayetteh', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 18);
insert into login_credentials (username, password, kind, user_id) values ('misaci', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 19);
insert into login_credentials (username, password, kind, user_id) values ('msummonsj', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 20);
insert into login_credentials (username, password, kind, user_id) values ('btucknuttk', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 21);
insert into login_credentials (username, password, kind, user_id) values ('lskahilll', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 22);
insert into login_credentials (username, password, kind, user_id) values ('bsherrellm', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 23);
insert into login_credentials (username, password, kind, user_id) values ('dfinlatorn', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 24);
insert into login_credentials (username, password, kind, user_id) values ('kmccarlieo', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 25);
insert into login_credentials (username, password, kind, user_id) values ('jcurdellp', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 26);
insert into login_credentials (username, password, kind, user_id) values ('orennelsq', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 27);
insert into login_credentials (username, password, kind, user_id) values ('dadamikr', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 28);
insert into login_credentials (username, password, kind, user_id) values ('asuscenss', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 29);
insert into login_credentials (username, password, kind, user_id) values ('mbravingtont', '$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG', 'client', 30);
insert into login_credentials (username, password, kind, user_id) VALUES ('username','$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG','client',31);


insert into user_favourites (category_id, user_id) values (10, 1);
insert into user_favourites (category_id, user_id) values (2, 2);
insert into user_favourites (category_id, user_id) values (3, 3);
insert into user_favourites (category_id, user_id) values (6, 4);
insert into user_favourites (category_id, user_id) values (1, 5);
insert into user_favourites (category_id, user_id) values (9, 6);
insert into user_favourites (category_id, user_id) values (10, 7);
insert into user_favourites (category_id, user_id) values (3, 8);
insert into user_favourites (category_id, user_id) values (2, 9);
insert into user_favourites (category_id, user_id) values (1, 10);
insert into user_favourites (category_id, user_id) values (8, 11);
insert into user_favourites (category_id, user_id) values (5, 12);
insert into user_favourites (category_id, user_id) values (8, 13);
insert into user_favourites (category_id, user_id) values (7, 14);
insert into user_favourites (category_id, user_id) values (2, 15);
insert into user_favourites (category_id, user_id) values (2, 16);
insert into user_favourites (category_id, user_id) values (10, 17);
insert into user_favourites (category_id, user_id) values (9, 18);
insert into user_favourites (category_id, user_id) values (4, 19);
insert into user_favourites (category_id, user_id) values (3, 20);
insert into user_favourites (category_id, user_id) values (3, 21);
insert into user_favourites (category_id, user_id) values (8, 22);
insert into user_favourites (category_id, user_id) values (1, 23);
insert into user_favourites (category_id, user_id) values (7, 24);
insert into user_favourites (category_id, user_id) values (1, 25);
insert into user_favourites (category_id, user_id) values (2, 26);
insert into user_favourites (category_id, user_id) values (1, 27);
insert into user_favourites (category_id, user_id) values (10, 28);
insert into user_favourites (category_id, user_id) values (7, 29);
insert into user_favourites (category_id, user_id) values (7, 30);

insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Man of the House', 'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', 66.87,  '2020-12-10', '2022-01-12', 4, 10);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Teenage Mutant Ninja Turtles: Turtles Forever', 'quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', 87.95,  '2020-04-29', '2021-08-12', 1, 2);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Young Aphrodites (Mikres Afrodites)', 'pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet', 48.82,  '2020-09-02', '2021-10-29', 2, 5);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Lila & Eve', 'in lectus pellentesque at nulla suspendisse potenti cras in purus', 79.5,  '2020-10-06', '2021-06-22', 4, 5);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Psycho III', 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 67.69,  '2020-11-20', '2021-07-23', 4, 7);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Off the Charts: The Song-Poem Story', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in', 60.17,  '2020-12-17', '2021-05-21', 3, 9);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Airheads', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 47.32,  '2021-03-26', '2022-01-16', 1, 5);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Mickey''s Once Upon a Christmas', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna', 80.87,  '2020-05-25', '2021-12-07', 4, 8);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Captive, The', 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh', 89.42,  '2020-08-22', '2021-07-06', 2, 8);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Rains Came, The', 'justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 72.22,  '2020-09-17', '2022-03-20', 5, 3);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Big Fat Liar', 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel', 11.46,  '2020-05-23', '2021-06-11', 29, 2);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Harmful Insect (Gaichu)', 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', 36.51,  '2020-12-12', '2021-07-03', 3, 6);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Antoine and Colette (Antoine et Colette)', 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat', 95.61,  '2021-02-24', '2021-07-12', 4, 3);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Rabbit-Proof Fence', 'at ipsum ac tellus semper interdum mauris ullamcorper purus sit', 59.35,  '2020-11-14', '2022-02-10', 11, 8);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Goofy Movie, A', 'suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc', 92.65,  '2020-08-14', '2022-02-20', 9, 10);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Love and Death', 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', 77.41,  '2020-06-05', '2021-09-01', 4, 6);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Brewster''s Millions', 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor', 5.64,  '2020-04-19', '2021-06-21', 20, 7);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Monsieur Ibrahim ', 'in faucibus orci luctus et ultrices posuere cubilia curae mauris', 59.32,  '2020-05-23', '2022-03-07', 24, 8);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Last Blitzkrieg, The', 'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', 31.46,  '2020-12-01', '2021-12-09', 4, 3);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('A Kind of America 2', 'neque duis bibendum morbi non quam nec dui luctus rutrum', 48.55,  '2021-03-07', '2021-10-21', 28, 2);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Warrior', 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed', 16.57,  '2020-08-14', '2021-06-23', 26, 6);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Soundtracker', 'dolor vel est donec odio justo sollicitudin ut suscipit a', 71.92,  '2020-10-31', '2021-08-16', 3, 5);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Yi Yi', 'pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue', 22.2,  '2020-06-12', '2021-10-21', 4, 4);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Who Is Killing the Great Chefs of Europe?', 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida', 21.91,  '2020-09-26', '2021-10-29', 4, 8);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('The Losers', 'sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at', 5.74,  '2021-01-03', '2021-07-14', 30, 8);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Greedy', 'vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 57.26,  null, '2022-02-22', 5, 9);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('La Soufrière - Warten', 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', 4.73,  null, '2022-02-15', 13, 1);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('War Horse', 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl', 56.07,  null, '2022-01-15', 26, 8);
insert into product (title, description, out_price, close_date, publish_date, vendor_id, category_id) values ('Raw Deal: A Question of Consent', 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc', 98.13,  null, '2021-09-12', 4, 5);

insert into bid (publish_date, amount, product_id, user_id) values ('2021-05-01 14:23:59', 37.57, 5, 26);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-07-06 02:20:12', 94.62, 16, 30);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-04-10 19:32:55', 63.4, 15, 12);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-02-05 19:39:26', 53.41, 16, 5);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-04-27 14:41:37', 77.84, 5, 4);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-01-29 19:58:08', 53.3, 27, 17);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-04-20 06:58:34', 11.16, 18, 23);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-06-11 06:15:04', 23.5, 20, 20);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-02-25 19:54:46', 58.55, 7, 15);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-02-23 11:04:51', 24.19, 6, 4);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-05-02 08:05:40', 29.74, 21, 6);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-07-30 22:36:17', 33.9, 22, 14);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-11-01 00:37:25', 34.05, 20, 23);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-07-20 16:36:07', 81.87, 29, 1);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-02-23 00:39:01', 98.52, 29, 29);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-10-30 18:17:55', 31.44, 27, 27);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-09-01 17:30:03', 4.69, 2, 26);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-01-29 00:36:52', 69.41, 17, 10);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-07-16 07:02:15', 20.41, 7, 2);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-11-18 14:14:45', 30.63, 19, 9);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-02-04 13:40:56', 32.49, 7, 19);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-03-13 07:05:59', 41.25, 16, 12);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-04-26 23:56:19', 32.63, 16, 2);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-04-13 09:12:49', 69.43, 23, 4);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-05-23 01:00:52', 96.78, 13, 19);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-11-23 09:45:11', 80.74, 14, 3);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-11-05 15:17:39', 58.19, 17, 24);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-03-14 23:29:40', 77.88, 19, 23);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-05-14 18:12:40', 65.61, 4, 3);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-10-18 01:28:22', 47.06, 18, 24);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-02-26 06:43:25', 34.99, 19, 10);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-10-20 20:34:14', 34.54, 28, 4);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-01-10 13:48:10', 15.89, 18, 13);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-06-05 19:31:44', 30.8, 1, 25);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-12-07 17:15:39', 25.97, 16, 6);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-08-21 13:55:26', 84.75, 10, 11);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-04-06 03:27:36', 27.79, 4, 28);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-02-28 15:26:32', 11.62, 5, 3);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-11-21 21:42:04', 90.63, 11, 22);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-01-08 09:33:00', 77.1, 26, 10);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-06-28 01:51:45', 10.04, 27, 10);
insert into bid (publish_date, amount, product_id, user_id) values ('2022-02-15 12:51:48', 91.38, 9, 13);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-09-26 03:39:13', 95.14, 19, 28);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-11-03 01:38:25', 60.98, 25, 27);
insert into bid (publish_date, amount, product_id, user_id) values ('2021-08-06 06:50:17', 89.32, 14, 8);

-- Admin accounts. password = BCrypt('password')
insert into login_credentials values ('admin','$2a$10$dLIkjXzk4L9q8YQ8cudI4O.44OO2ii5Cu9F00AtjHx.31lP9TZpAG','admin',null)